#!/usr/bin/env node
// Stamp a new build id into js/version.js, version.json and sw.js so installed copies of
// the site notice the update and reload themselves (see js/app.js checkForUpdate).
//   node pipeline/stamp.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const d = new Date();
const pad = (n) => String(n).padStart(2, '0');
const build = `${d.getUTCFullYear()}.${pad(d.getUTCMonth() + 1)}.${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}`;

writeFileSync(join(ROOT, 'js', 'version.js'), `// Generated by pipeline/stamp.mjs\nexport const BUILD = '${build}';\n`);
writeFileSync(join(ROOT, 'version.json'), JSON.stringify({ build }) + '\n');
const sw = join(ROOT, 'sw.js');
writeFileSync(sw, readFileSync(sw, 'utf8').replace(/const VERSION = '[^']*';/, `const VERSION = '${build}';`));
console.log(`build ${build}`);
