#!/usr/bin/env node
// Builds js/icons.js: an SVG <symbol> sprite from Lucide (ISC) plus two drawn icons.
//   node pipeline/tools/build-icons.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const LUCIDE = join(ROOT, 'node_modules', 'lucide-static', 'icons');

const NAMES = [
  'search', 'sliders-horizontal', 'x', 'chevron-down', 'chevron-left', 'chevron-right', 'arrow-left',
  'arrow-up-right', 'map-pin', 'calendar-days', 'ticket', 'globe', 'users', 'share-2', 'link', 'check',
  'arrow-up-down', 'sun', 'moon', 'image-off', 'info', 'user-round', 'clock', 'rotate-ccw', 'copy',
];

// Drawn in the same 24px / 2px-stroke grammar as Lucide.
const CUSTOM = {
  // A strap meeting at a clip, holding a badge.
  lanyard:
    '<path d="M5 2.5 12 10l7-7.5"/><circle cx="12" cy="11.5" r="1.5"/><rect x="7" y="14" width="10" height="7.5" rx="1.5"/><path d="M10 17.5h4"/>',
  // The badge clip itself (empty = not saved).
  clip: '<circle cx="12" cy="4.5" r="2.5"/><path d="M12 7v2.5"/><path d="M8.5 9.5h7v6.25a3.5 3.5 0 0 1-7 0z"/><path d="M12 13v4"/>',
};

const inner = (svg) =>
  svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();

const symbols = [];
for (const n of NAMES) symbols.push(`<symbol id="i-${n}" viewBox="0 0 24 24">${inner(readFileSync(join(LUCIDE, `${n}.svg`), 'utf8'))}</symbol>`);
for (const [n, body] of Object.entries(CUSTOM)) symbols.push(`<symbol id="i-${n}" viewBox="0 0 24 24">${body}</symbol>`);

const out = `// Generated by pipeline/tools/build-icons.mjs. Lucide icons (ISC licence) + drawn lanyard/clip.
export const SPRITE = ${JSON.stringify(
  `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="0" height="0" style="position:absolute;overflow:hidden" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${symbols.join('')}</svg>`,
)};

export const icon = (name, cls = '') => \`<svg class="icon\${cls ? ' ' + cls : ''}" aria-hidden="true"><use href="#i-\${name}"/></svg>\`;
`;
writeFileSync(join(ROOT, 'js', 'icons.js'), out);
console.log(`js/icons.js: ${symbols.length} icons`);
